name: Merge Group

on:
  merge_group:
    types: [destroyed]

jobs:
  log:
    name: Log Event
    runs-on: ubuntu-latest
    steps:
      - name: Log Event
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
