name: Push

on:
  push:
    branches: [ merge-queue ]

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:
      - name: Log Event
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
