name: Release

on:
  push:
    branches:
      - main
      - merge-queue

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Log Event
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
