name: Release

on:
  pull_request:
    branches:
      - main
      - merge-queue
    types:
      - closed

jobs:
  if: github.event.pull_request.merged == true
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Log Event
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
