name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Lint
        run: yarn lint

      - name: Run Unit Tests
        run: yarn test

      - name: Package
        run: yarn package

      - name: Compare the expected and actual dist/ directories
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Detected uncommitted changes after build. See status below:"
            git status
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git add dist/
            git commit -m "chore: comitting generated dist"
            git push
            exit 1
          fi

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Package Json
        uses: ./
        with:
          rules: |
            ranges
            tags
