name: Build and Test

on:
  pull_request:
    branches:
      - main
      - merge-queue
  merge_group:
    types:
      - checks_requested

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: No-op
        run: sleep 180 && echo "no-op"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: No-op
        run: sleep 180 && echo "no-op"
